from app.ai.gemini import generate_json
from app.ai.prompts import learning_topic_detail_prompt
from app.database.db import supabase


def generate_learning_path(role: str, skills: list):

    prompt = f"""
You are an experienced software engineering career mentor and hiring manager.

Recommended Role:
{role}

Current Skills:
{skills}

Your task is to create a personalized learning path.

Rules:

1. Recommend ONLY the most important skills required to become job-ready for this role.

2. Select ONLY 6 skills.

3. Arrange them in the correct learning order.

4. Compare each skill with Current Skills.

5. If the exact skill exists:
   - status = completed
   - progress = 100

6. If the user has completed all previous skills but not this one:
   - status = in_progress
   - progress = choose a realistic value between 40 and 80

7. All remaining skills:
   - status = pending
   - progress = 0

8. Every skill must contain:
   - skill
   - level (Beginner / Intermediate / Advanced)
   - duration
   - status
   - progress
   - short_description

9. short_description must be ONE concise sentence (under 18 words) describing what the student will learn/be able to do - written for a vertical list row, not a paragraph.

10. Maximum ONE skill can have status "in_progress".

11. Never assume similar technologies are the same.

Examples:
Python ≠ Java
SQL ≠ PostgreSQL
React ≠ Next.js
FastAPI ≠ Flask

Return ONLY valid JSON.

Example:

{{
    "role": "{role}",
    "learning_path": [
        {{
            "skill": "Python",
            "level": "Beginner",
            "duration": "2 Weeks",
            "status": "completed",
            "progress": 100,
            "short_description": "Learn core Python syntax, data structures, and scripting fundamentals."
        }},
        {{
            "skill": "Data Structures",
            "level": "Intermediate",
            "duration": "3 Weeks",
            "status": "completed",
            "progress": 100,
            "short_description": "Master arrays, trees, graphs, and hash maps for efficient problem solving."
        }},
        {{
            "skill": "Machine Learning",
            "level": "Intermediate",
            "duration": "5 Weeks",
            "status": "in_progress",
            "progress": 65,
            "short_description": "Build and evaluate supervised and unsupervised ML models from scratch."
        }},
        {{
            "skill": "Deep Learning",
            "level": "Advanced",
            "duration": "4 Weeks",
            "status": "pending",
            "progress": 0,
            "short_description": "Design neural networks for vision and language tasks using modern frameworks."
        }},
        {{
            "skill": "MLOps",
            "level": "Advanced",
            "duration": "3 Weeks",
            "status": "pending",
            "progress": 0,
            "short_description": "Deploy, monitor, and version ML models reliably in production."
        }},
        {{
            "skill": "System Design",
            "level": "Advanced",
            "duration": "2 Weeks",
            "status": "pending",
            "progress": 0,
            "short_description": "Design scalable, reliable systems and reason about real-world trade-offs."
        }}
    ]
}}
"""

    return generate_json(prompt)


# ---------------------------------------------------------------------
# Learning Details ("Start Learning") - see routes/learning_path.py.
#
# Content is scoped to (role, skill), not per-student: the in-depth
# guide for e.g. "Backend Developer -> PostgreSQL" is identical
# regardless of who's viewing it, so it's generated by Gemini exactly
# ONCE per (role, skill) pair, ever, and every later "Start Learning"
# click for that same pair - by this student or any other student on
# the same role - is served straight from Supabase with zero Gemini
# calls. This mirrors certificate_recommendation_service's
# generate-once-then-persist pattern, applied at the (role, skill)
# level instead of the per-email level, and reuses the exact same
# generate_json() Gemini client - no second client, no second
# failover system.
# ---------------------------------------------------------------------

def get_or_generate_topic_details(role: str, skill: str, level: str, duration: str) -> dict:
    existing = (
        supabase
        .table("learning_path_topic_details")
        .select("*")
        .eq("role", role)
        .eq("skill", skill)
        .limit(1)
        .execute()
    )

    if existing and existing.data:
        return existing.data[0]["details"]

    prompt = learning_topic_detail_prompt(role, skill, level, duration)
    details = generate_json(prompt)

    # Upsert against the UNIQUE(role, skill) constraint (see
    # backend/migrations/2026_08_08_learning_path_and_jobs_and_certs.sql)
    # rather than a plain insert, so two near-simultaneous "Start
    # Learning" clicks for the same never-yet-generated (role, skill)
    # pair - by this student or a different one - can never create two
    # duplicate rows or trigger two Gemini calls that both "win".
    supabase.table("learning_path_topic_details").upsert(
        {
            "role": role,
            "skill": skill,
            "details": details,
        },
        on_conflict="role,skill",
    ).execute()

    return details
